name = "RotinasOtim"
uuid = "3c2bcae1-b8f2-44ea-97fb-f8169ba2b0c6"
authors = ["Eduardo Lenz <eduardobarplenz@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
